### ISSUE TITLE
Can turning off an input/CEC turn off the TV?

### ISSUE THREAD

**Issue by epheterson** [SeydX/homebridge-sonybravia-platform#10]
I like how I can turn on both the TV and Apple TV with one switch now (The Apple TV CEC). It'd then be great to also turn off the whole setup with the same switch.

For this to be possible, we'd need to pick between launching a home app on close, or sending the off command. Perhaps there could be a setting in the config to control it?

**Comment by seydx** [comment]
So you want an option to define an "own" way of putting a cec device off? Atm it will always start the "home app" after switching cec off

**Comment by seydx** [comment]
I think i will add an option to change the "off command" of an cec device to select between "home app, favourite channel or tv off" in the next version

**Comment by epheterson** [comment]
I was thinking make the setting global? So if I turn off an HDMI input, or a CEC, use the same setting - home app or power off. It’s less clunky than defining it per-source, and likely people who change it will want it to apply to all (I think). 

Either way, though! Even for just CEC, it’s useful.

**Comment by epheterson** [comment]
Oh wait, I realized the Apple TV CEC switch doesn’t stay on when the Apple TV is on. That kinda breaks this idea, is there any way to keep it on? 

Maybe keep it on until the next power cycle, or input change?

**Comment by seydx** [comment]
No i dont mean defining per source. I will add a "global" option to the config file. So everyone has then the possibility to set his own global "off comand" for the inputs like hdmi or cec devices. And it will the same for all inputs, not per source.

** After switching Apple TV on, can you run following command and post the output here pls:
_(change ip and psk with your own data)_

> curl -XPOST http://192.168.1.1/sony/avContent -d '{"id":2,"method":"getPlayingContentInfo","version":"1.0","params":["1.0"]}' -H 'X-Auth-PSK: abc123'

**Comment by epheterson** [comment]
Output is correct, the CEC device is connected to HDMI port 4:
`{"id":2,"result":[{"source":"extInput:hdmi","title":"HDMI 4","uri":"extInput:hdmi?port=4"}]}`

I think it's safe to infer that the input selected after CEC command is the same as the CEC device – so until it changes, keep the CEC device "on"?

**Comment by seydx** [comment]
The plugin checks the uri in the playing content info and compares it with the uri from the accesory. If both are equal, the switch will turn on, if not the switch will turn off

Normally, the HDMI input has an another uri as the cec device. But i created a own "simple uri" to compare the current uri from the API with the uri from accessory and the simple uri

The simple uri contains "extInput:hdmi?port=" + port number

normally it must stay on, i think there is an issue with splitting the uri for the port number.. 
Can you open the src/Inputs.js file and put following code after line 49

> this.log(this.name + ": " + this.simpleuri);

and post the output after restarting homebridge pls

**Comment by epheterson** [comment]
```
[2018-3-26 12:30:21] [Sony] CEC devices found in storage.
[2018-3-26 12:30:21] [Sony] Sony Player 1: extInput:hdmi?port=1
[2018-3-26 12:30:21] [Sony] Sony HDMI 2: extInput:hdmi?port=2
[2018-3-26 12:30:21] [Sony] Sony HDMI 3: extInput:hdmi?port=3
[2018-3-26 12:30:21] [Sony] Sony HDMI 4: extInput:hdmi?port=4
[2018-3-26 12:30:21] [Sony] Found 4 HDMI input(s) with 1 CEC device(s), 0 extra input(s), 386 app(s) and 0 channel(s)
```

What's appearing as Sony Player 1 is my CEC device that turns on the Apple TV, I think. Seems it may be incorrectly identified as HDMI 1? I just verified in the TV UI, and the Apple TV is connected to HDMI 4.

**Comment by seydx** [comment]
hmm can you add following code after the first code too

> this.log(this.name + ": " + this.uri);

and post the output pls

**Comment by epheterson** [comment]
Looks like Sony Player 1 is mapping to the wrong HDMI port:
```
[2018-3-26 14:40:57] [Sony] CEC devices found in storage.
[2018-3-26 14:40:57] [Sony] Sony Player 1: extInput:hdmi?port=1
[2018-3-26 14:40:57] [Sony] Sony Player 1: extInput:cec?type=player&port=1
[2018-3-26 14:40:57] [Sony] Sony HDMI 2: extInput:hdmi?port=2
[2018-3-26 14:40:57] [Sony] Sony HDMI 2: extInput:hdmi?port=2
[2018-3-26 14:40:57] [Sony] Sony HDMI 3: extInput:hdmi?port=3
[2018-3-26 14:40:57] [Sony] Sony HDMI 3: extInput:hdmi?port=3
[2018-3-26 14:40:57] [Sony] Sony HDMI 4: extInput:hdmi?port=4
[2018-3-26 14:40:57] [Sony] Sony HDMI 4: extInput:hdmi?port=4
[2018-3-26 14:40:57] [Sony] Found 4 HDMI input(s) with 1 CEC device(s), 0 extra input(s), 386 app(s) and 0 channel(s)
```

**Comment by seydx** [comment]
can you remove the hdmi and cec cache files in storage (in persist folder) and try it again pls

**Comment by epheterson** [comment]
Yeah same output.

**Comment by epheterson** [comment]
I think I see the problem, looks like you're overlaying these two when they should be unique, because they both have port=1:
```
			"connection": false,
			"icon": "meta:hdmi",
			"label": "",
			"title": "HDMI 1/MHL",
			"uri": "extInput:hdmi?port=1"
		}, {
...
		}, {
			"connection": true,
			"icon": "meta:playbackdevice",
			"label": "Apple TV",
			"title": "Player 1",
			"uri": "extInput:cec?type=player&port=1"
		}, {
```
Total output of Sony_Inputs cache:
`{"id":1,"result":[[{"connection":false,"icon":"meta:hdmi","label":"","title":"HDMI 1/MHL","uri":"extInput:hdmi?port=1"},{"connection":false,"icon":"meta:hdmi","label":"","title":"HDMI 2","uri":"extInput:hdmi?port=2"},{"connection":false,"icon":"meta:hdmi","label":"","title":"HDMI 3","uri":"extInput:hdmi?port=3"},{"connection":true,"icon":"meta:hdmi","label":"","title":"HDMI 4","uri":"extInput:hdmi?port=4"},{"connection":true,"icon":"meta:composite","label":"","title":"Video 1","uri":"extInput:composite?port=1"},{"connection":false,"icon":"meta:component","label":"","title":"Video 2/Component","uri":"extInput:composite?port=2"},{"connection":true,"icon":"meta:playbackdevice","label":"Apple TV","title":"Player 1","uri":"extInput:cec?type=player&port=1"},{"connection":false,"icon":"meta:wifidisplay","label":"","title":"Screen mirroring","uri":"extInput:widi?port=1"}]]}`

**Comment by seydx** [comment]
The global option for setting own "off state command" is done
v2.4.2 is up

lats take a look to the cec state bug

**Comment by seydx** [comment]
can i see the Sony_CEC storage file pls

**Comment by epheterson** [comment]
Works just as expected, thanks! I do have to use my HDMI_4 toggle to test it, so let's see if we can get this CEC things figured out. 

Here's the output of Sony_CEC, looks like it's the same for both:
`{"id":1,"result":[[{"connection":false,"icon":"meta:hdmi","label":"","title":"HDMI 1/MHL","uri":"extInput:hdmi?port=1"},{"connection":false,"icon":"meta:hdmi","label":"","title":"HDMI 2","uri":"extInput:hdmi?port=2"},{"connection":false,"icon":"meta:hdmi","label":"","title":"HDMI 3","uri":"extInput:hdmi?port=3"},{"connection":true,"icon":"meta:hdmi","label":"","title":"HDMI 4","uri":"extInput:hdmi?port=4"},{"connection":true,"icon":"meta:composite","label":"","title":"Video 1","uri":"extInput:composite?port=1"},{"connection":false,"icon":"meta:component","label":"","title":"Video 2/Component","uri":"extInput:composite?port=2"},{"connection":true,"icon":"meta:playbackdevice","label":"Apple TV","title":"Player 1","uri":"extInput:cec?type=player&port=1"},{"connection":false,"icon":"meta:wifidisplay","label":"","title":"Screen mirroring","uri":"extInput:widi?port=1"}]]}`

**Comment by seydx** [comment]
lets look at index.js and directly to the api

can you open index.js and put following code after line 588:

> self.log(result[i].title + ": " + uri);

after then, restart homebridge and post the output pls

**Comment by epheterson** [comment]
`[2018-3-26 17:06:52] [Sony] Player 1: extInput:cec?type=player&port=1`

**Comment by seydx** [comment]
Are you sure that you plugged in the cec device to port 4??

can you run following command and post the FULL output here pls:
_(TV must be on)_

if you have jq installed, please use this command
> curl -XPOST http://192.168.1.1/sony/avContent -d '{"id":2,"method":"getCurrentExternalInputsStatus","version":"1.0","params":["1.0"]}' -H 'X-Auth-PSK: abc123' | jq

if you **don't** have jq installed, please use this command
> curl -XPOST http://192.168.1.1/sony/avContent -d '{"id":2,"method":"getCurrentExternalInputsStatus","version":"1.0","params":["1.0"]}' -H 'X-Auth-PSK: abc123'

**Comment by epheterson** [comment]
Hey, it's definitely plugged into HDMI 4, I think this version of Sony Bravia maps ports differently, is the issue. That is, type=player&port=1 (in cec) is not the same as port=1 (in HDMI). 

Here's the formatted output:
```
{
  "id": 2,
  "result": [
    [
      {
        "connection": false,
        "icon": "meta:hdmi",
        "label": "",
        "title": "HDMI 1/MHL",
        "uri": "extInput:hdmi?port=1"
      },
      {
        "connection": false,
        "icon": "meta:hdmi",
        "label": "",
        "title": "HDMI 2",
        "uri": "extInput:hdmi?port=2"
      },
      {
        "connection": false,
        "icon": "meta:hdmi",
        "label": "",
        "title": "HDMI 3",
        "uri": "extInput:hdmi?port=3"
      },
      {
        "connection": true,
        "icon": "meta:hdmi",
        "label": "",
        "title": "HDMI 4",
        "uri": "extInput:hdmi?port=4"
      },
      {
        "connection": true,
        "icon": "meta:composite",
        "label": "",
        "title": "Video 1",
        "uri": "extInput:composite?port=1"
      },
      {
        "connection": false,
        "icon": "meta:component",
        "label": "",
        "title": "Video 2/Component",
        "uri": "extInput:composite?port=2"
      },
      {
        "connection": true,
        "icon": "meta:playbackdevice",
        "label": "Apple TV",
        "title": "Player 1",
        "uri": "extInput:cec?type=player&port=1"
      },
      {
        "connection": false,
        "icon": "meta:wifidisplay",
        "label": "",
        "title": "Screen mirroring",
        "uri": "extInput:widi?port=1"
      }
    ]
  ]
}
```

**Comment by seydx** [comment]
The problem is, the api says the apple tv is plugged in port 1, because of that it uses the value "1" for the uri.. 

can you plug in your apple tv in port 1,  restart your tv, run the code above again and save the output pls.

after then, plug in to port 4 again, run the code and compare the results pls or just post both results here pls

**Comment by epheterson** [comment]
This is it plugged into HDMI 3, the playback device itself doesn't change. All that changed is now HDMI 3 is connection:true. The port=1 from meta:playbackdevice on cec is not at all the same as a port=1 in meta:hdmi. That's the crux of the issue, I think on some models it is the same, but on mine it is not. I've already gone through the CEC UI on my TV and confirmed `extInput:cec?type=player&port=1` didn't change to anything else. Also, if I change ports, and without relaunching homebridge or restarting the TV, I can turn it "on" in HomeKit, and it corrects to the correct HDMI port. This means that it's mapping port=1 to the *device* and not the port.

I notice this *does* say connection:true, and I have to imagine the same item is what's being used to create the toggle. Why not just use the connection:true on this property to control the state of the toggle?
```
      {
        "connection": true,
        "icon": "meta:playbackdevice",
        "label": "Apple TV",
        "title": "Player 1",
        "uri": "extInput:cec?type=player&port=1"
      },
```

Output:
```
{
  "id": 2,
  "result": [
    [
      {
        "connection": false,
        "icon": "meta:hdmi",
        "label": "",
        "title": "HDMI 1/MHL",
        "uri": "extInput:hdmi?port=1"
      },
      {
        "connection": false,
        "icon": "meta:hdmi",
        "label": "",
        "title": "HDMI 2",
        "uri": "extInput:hdmi?port=2"
      },
      {
        "connection": true,
        "icon": "meta:hdmi",
        "label": "",
        "title": "HDMI 3",
        "uri": "extInput:hdmi?port=3"
      },
      {
        "connection": false,
        "icon": "meta:hdmi",
        "label": "",
        "title": "HDMI 4",
        "uri": "extInput:hdmi?port=4"
      },
      {
        "connection": true,
        "icon": "meta:composite",
        "label": "",
        "title": "Video 1",
        "uri": "extInput:composite?port=1"
      },
      {
        "connection": false,
        "icon": "meta:component",
        "label": "",
        "title": "Video 2/Component",
        "uri": "extInput:composite?port=2"
      },
      {
        "connection": true,
        "icon": "meta:playbackdevice",
        "label": "Apple TV",
        "title": "Player 1",
        "uri": "extInput:cec?type=player&port=1"
      },
      {
        "connection": false,
        "icon": "meta:wifidisplay",
        "label": "",
        "title": "Screen mirroring",
        "uri": "extInput:widi?port=1"
      }
    ]
  ]
}
```

**Comment by seydx** [comment]
i need a "unique" value to compare the api with the accessory data for the state

the value for connection is not really unique (true), and that will cause that other cec devices (in my case the ps4) will turn on too

i think thats not normal that it stays at port 1... have already looked at bravia sync menu??

**Comment by epheterson** [comment]
Oh that's a good point, yeah it stays connection:true even when I don't have the Apple TV on.

So, my Sony TV handles things differently than others. The port 1 in `extInput:cec?type=player&port=1` is not the same as the port 1 in `extInput:hdmi?port=1`.

With that being the case, I can either plug it into port1 and trick your plugin into doing the right thing, or the plugin would have to infer which CEC device is mapped to which HDMI port and use that inference to control the tile state.

Edit: Yeah plugging it into HDMI 1 gives me what I want, but only by tricking the plug-in. Should we track this separately as a bug?

**Comment by seydx** [comment]
**extInput:hdmi?port=1** doesnt activate the cec device, only switch to HDMI 1
**extInput:cec?type=player&port=1** activates the cec device plugged in HDMI 1

Thats the different between them. And the plugin use both uri's to compare with the api. If the accessory is a cec device, it has normally this uri: "extInput:cec?type=player&port=1" - but sometimes, even if the cec device is active and turned on, the api says that the currently active uri is "extInput:hdmi?port=1"

because of that, the plugin compares the currently active uri from the api, with the own device uri AND an own created simple uri "'extInput:hdmi?port=' + port number of the cec device"

so if the api display a wrong port number, the state check will fail.

The plugin can only derive the right cec device and port when the api says the right thing. otherwise we have only the possiblity to give them manually a port number withing config.json

**Comment by epheterson** [comment]
The API isn't exactly lying, it behaves differently between different models. Believe me, I understand the frustration! It's a bit unfair to a developer for Sony to have multiple similar implementations in the wild, all needing to be supported by common code.

On my TV, extInput:cec?type=player&port=1 does not activate the CEC device on HDMI 1 – it activates the first CEC device. Based on what we've seen, the array of HDMI ports does not intersect with the array of CEC devices, thus the identifiers do not overlap.

I think you're taking `port=1` to literally mean HDMI port 1, when in reality it can mean index of 1 on any set. 

Note that also the Composite and Screen Mirroring options are on port 1, in their respective sets:
```
      {
        "connection": true,
        "icon": "meta:composite",
        "label": "",
        "title": "Video 1",
        "uri": "extInput:composite?port=1"
      },
      {
        "connection": false,
        "icon": "meta:component",
        "label": "",
        "title": "Video 2/Component",
        "uri": "extInput:composite?port=2"
      },
      {
        "connection": true,
        "icon": "meta:playbackdevice",
        "label": "Apple TV",
        "title": "Player 1",
        "uri": "extInput:cec?type=player&port=1"
      },
      {
        "connection": false,
        "icon": "meta:wifidisplay",
        "label": "",
        "title": "Screen mirroring",
        "uri": "extInput:widi?port=1"
      }
```

**Comment by seydx** [comment]
ahh i understand what u mean. i will look above the code, maybe i can create something to fix the problem

**Comment by seydx** [comment]
but to be sure, do you have any other cec devices that you can plug in? to control if this what u think is true.

That is my output:
```
{
	"result": [
		[
			{
				"uri": "extInput:cec?type=player&port=3&logicalAddr=4",
				"title": "PlayStation 4",
				"connection": true,
				"label": "",
				"icon": "meta:playbackdevice"
			},
			{
				"uri": "extInput:cec?type=player&port=2&logicalAddr=8",
				"title": "Apple TV",
				"connection": true,
				"label": "",
				"icon": "meta:playbackdevice"
			},
			{
				"uri": "extInput:hdmi?port=1",
				"title": "HDMI 1",
				"connection": false,
				"label": "HDMI 1",
				"icon": "meta:hdmi"
			},
			{
				"uri": "extInput:hdmi?port=2",
				"title": "HDMI 2",
				"connection": true,
				"label": "HDMI 2",
				"icon": "meta:hdmi"
			},
			{
				"uri": "extInput:hdmi?port=3",
				"title": "HDMI 3\/ARC",
				"connection": false,
				"label": "HDMI 3",
				"icon": "meta:hdmi"
			},
			{
				"uri": "extInput:hdmi?port=4",
				"title": "HDMI 4",
				"connection": false,
				"label": "HDMI 4",
				"icon": "meta:hdmi"
			},
			{
				"uri": "extInput:scart?port=1",
				"title": "AV 1",
				"connection": true,
				"label": "",
				"icon": "meta:scart"
			},
			{
				"uri": "extInput:composite?port=1",
				"title": "AV 2",
				"connection": false,
				"label": "",
				"icon": "meta:composite"
			},
			{
				"uri": "extInput:widi?port=1",
				"title": "Bildschirm spiegeln",
				"connection": true,
				"label": "",
				"icon": "meta:wifidisplay"
			}
		]
	],
	"id": 2
}
```

as u can see, mirroring has also a port number, but the cec devices are not listed as u said, thats are listed with the right port number

**Comment by epheterson** [comment]
Unfortunately I don't have another CEC device, but yeah ours are definitely behaving differently. It seems when logicalAddr is missing, port no longer maps to HDMI ports.

**Comment by seydx** [comment]
i would control this before changing the lines :/ therefore it would be very nice if u had a second cec device on a different port to control the ports. Then we can see if the api is lying or your ports are sorted on connected devices and not on connected ports

**Comment by epheterson** [comment]
I can try to get one maybe tomorrow, but it's clearly sorting by connected devices. 

I did a test where I changed the Apple TV port physically, then turned it on with the same `extInput:cec?type=player&port=1` command in homebridge. This could only be possible if it were mapping to the device, and not the port.

I'm fairly certain that the next CEC device would be `extInput:cec?type=player&port=2`

This theory fits if you look at the output of my composite ports:
```
      {
        "connection": true,
        "icon": "meta:composite",
        "label": "",
        "title": "Video 1",
        "uri": "extInput:composite?port=1"
      },
      {
        "connection": false,
        "icon": "meta:component",
        "label": "",
        "title": "Video 2/Component",
        "uri": "extInput:composite?port=2"
      },
```

**Comment by seydx** [comment]
Allright, then i will try to change it. But i dont really know how the plugin could detect on which port the cec device is, if the api doesnt say anything in regard of the port :/ hmm

any ideas?

**Comment by epheterson** [comment]
Yeah not super easy, but I was suggesting it could infer it. It can check which port is selected before sending the CEC command, and which a moment after, then store the connection (verifying again each time?).

**Comment by epheterson** [comment]
You could also just leave it to users (me) to do the mapping!

**Comment by seydx** [comment]
im on it, can you say me wich hdmi ports are currently exposed in your homekit? hdmi2, hdmi3 and hdmi4?

or do you also have hdmi1?

**Comment by epheterson** [comment]
Hey, yeah that's correct I have HDMI 2, 3, 4 and the CEC toggle.

**Comment by seydx** [comment]
ok thanks

**Comment by seydx** [comment]
so i think im finished, new version is coming

**Comment by seydx** [comment]
v2.4.3 is up

please add following option to your config.json:
```
"cecDevices":[
    {
      "title":"Player 1",
      "hdmiport":4
    }
]
```

**Comment by seydx** [comment]
forgotten to upload the Input.js file >.<

v2.4.4 is up

**Comment by epheterson** [comment]
Hey! Pretty good, except it looks like my ATV CEC switch (`extInput:cec?type=player&port=1`) stays on when HDMI 1 (`extInput:hdmi?port=1`) is on, when I have my ATV attached to HDMI 4. It turns off when ports don't match, e.g. HDMI 3. Not the end of the world, but looks like an oversight, looks like it's still matching port=1 together.

**Comment by seydx** [comment]
The uri to activate the cec device takes the plugin always from api, but i changed the code to compare the api with the cec device to fix the state problem

if you change the hdmi port from i.e. 1 to 4, you need always change your config hdmiport, it can not detect automatically

by the way, 2.5 is up with new remote control function :)

i think we can close this issue now?

**Comment by epheterson** [comment]
Oh, hmm... I thought I was hitting a bug but it's not reproducing anymore. What I was seeing is that HDMI 1 toggle would stay lit regardless of which HDMI the Apple TV was plugged into (i.e. two inputs lit simultaneously) while the config setting was correct. 

Anywho, since it's not happening anymore, yeah I think this bug is closed! Thanks!

Of to checking into this remote...
