### ISSUE TITLE
Switching to TV

### ISSUE THREAD

**Issue by franzel61** [SeydX/homebridge-sonybravia-platform#2]
Hello, I have installed the plugin 1 week ago, however after switching to adifferent channel like AppleTV i can switch back to TV... what do I wrong

**Comment by seydx** [comment]
Hello,

I dont understand your Problem :/

So if you Change to Apple TV you can't Change Back to TV? What exactly you mean?

**Comment by franzel61** [comment]
Hello 

If I use Siri and switch to Apple TV than works fine, which command I have to use to switch back to broadcast TV?

Mit freundlichen Gruessen / Best regards 
Franzel

**Comment by seydx** [comment]
Du möchtest wissen wie man von zB Apple TV wieder zurück zu einem Kanal wechselt? Kanalfunktion ist noch nicht implementiert, kommt erst in einer späteren Version

Lg

**Comment by franzel61** [comment]
Ja richtig .... wieder zurück zum “alten” Kanal wäre schon gut ....

Wann ist es ca geplant das zu implementieren?

Grob 


Mit freundlichen Gruessen / Best regards 
Franzel Rudison

**Comment by seydx** [comment]
Zurück zum 'alten' Kanal wird denke ich nicht möglich sein, genauer weiß ich es aber wenn ich die Zeit finde mich dran zu setzen

Noch bin ich mit einem andem Plugin beschäftigt, sobald diese fertiggestellt ist wird es angegangen

**Comment by franzel61** [comment]
Schönen Dank für die Informationen
Ich freue mich auf die Erweiterung 

Mit freundlichen Gruessen / Best regards 
Franzel Rudison

**Comment by seydx** [comment]
Mit 2.1 wurde jetzt die Möglichkeit hinzugefügt via Szenen Channels auszuwählen! 

LG

**Comment by franzel61** [comment]
Danke

Mit freundlichen Gruessen / Best regards 
Franzel Rudison
