### ISSUE TITLE
Cannot control volume

### ISSUE THREAD

**Issue by ryanxu36** [SeydX/homebridge-sonybravia-platform#3]
Everything works great except the volume controller, the volume bar just appear when I adjust the bulb in home app, but it does not actually control the volume. I have no idea how to fix it..help..
Great plugin, thanks!

**Comment by seydx** [comment]
Hello

So you See the bulb but it dont do anything? Can you Post your config please and your Log?

**Comment by seydx** [comment]
Already tried with the latest release?

**Comment by seydx** [comment]
Im closing this issue now, if you have problems with the latest release, please add a new issue
