### ISSUE TITLE
Enhancement: Allow setting of Home App with Apps service

### ISSUE THREAD

**Issue by epheterson** [SeydX/homebridge-sonybravia-platform#5]
The app service is a nice way to open apps, and it displays both the current and home app, but it'd be cool if it also allowed setting of the home app. All it would need is one more toggle, I suppose this would mandate that it's not set it the config file as well.

**Comment by seydx** [comment]
Yes that would be nice, i will try to implement this

**Comment by seydx** [comment]
added in v2.3
