### ISSUE TITLE
Volume slider should show proper % when maxVolume is set

### ISSUE THREAD

**Issue by epheterson** [SeydX/homebridge-sonybravia-platform#9]
The lightbulb brightness in the app is 100% always, regardless of what maxVolume is set to in config.json. You should override the max brightness to the maxVolume value so that you get both a smaller range / more control in the slider, and an accurate number displayed in the app.

**Comment by seydx** [comment]
>this.VolumeBulb.addCharacteristic(new Characteristic.Brightness())
.setProps({
maxValue: self.maxVolume,
minValue: 0,
minStep: 1
})

max Brightness is already = max Volume setted in the config.json file. But i think you want that if volume = 17 than brightness in the app also be 17%

**Comment by seydx** [comment]
Should be fixed in https://github.com/SeydX/homebridge-sonybravia-platform/commit/1d903f8ced49a4990c065da8ff9a5a1d7339d6c6

new Version is on the way
